{"name": "test_login3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_login.TestLogin object at 0x0000020B7A81AA58>\n\n    def test_login3(self):\n        print(\"4\")\n>       assert 0\nE       assert 0\n\nscripts\\test_login.py:13: AssertionError"}, "start": 1583383446341, "stop": 1583383446342, "uuid": "78c64996-24ea-4a23-93c1-a0619cdcbe28", "historyId": "8e257269297f526cfe5c70e4827d2e66", "testCaseId": "2ef86964a43e530ba9a46d4c42bb9c07", "fullName": "scripts.test_login.TestLogin#test_login3", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-3F0E0K8M"}, {"name": "thread", "value": "8716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}